# Generated by Django 3.0.6 on 2020-10-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skilltree', '0002_auto_20201010_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='#')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltree.SkillTree')),
            ],
        ),
    ]
