# Generated by Django 3.0.6 on 2020-10-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='column',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
