# Generated by Django 3.0.6 on 2020-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('link_id', models.URLField()),
                ('description_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('disabled', models.BooleanField()),
            ],
        ),
    ]
