# Generated by Django 3.0.6 on 2020-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltree',
            name='node_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='skilltree',
            name='link_id',
            field=models.CharField(max_length=100),
        ),
    ]
