# Generated by Django 3.0.6 on 2020-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=50)),
                ('tree_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
