# Generated by Django 3.0.6 on 2020-10-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltree',
            old_name='tree_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='skilltree',
            old_name='tree_name',
            new_name='name',
        ),
    ]
